# Generated by Django 4.1.2 on 2022-10-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
